version: '3.8'

services:
  app:
    build:
      context: ./blockchain-price-tracker
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=price_tracker
      - EMAIL_USER=your_email@gmail.com
      - EMAIL_PASS=your_password
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: price_tracker
    ports:
      - "3306:3306"
